### ISSUE TITLE
File "/usr/local/lib/python3.7/site-packages/pydot.py", line 1933, in create raise OSError(*args) FileNotFoundError: [Errno 2] "dot" not found in path.

### ISSUE THREAD

**Issue by vikram-nunna** [pydot/pydot#284] opened 2022-03-28 10:55 UTC
I am using pydot to generate graph and i installed graphviz, my program has to run in docker when i tried locally i copied files of graphviz to folder where my code exists and added these lines 
os.environ["PATH"] += os.pathsep + os.getcwd()+'/Graphviz2.38/bin/'
os.environ["PATH"] += os.pathsep + os.getcwd()+'/Graphviz2.38/lib/'
I removed path from environment variable its worked fine in local but when trying in docker its raising error

**Comment by vikram-nunna** [comment] 2022-03-28 11:00
FROM python:3.7

RUN pip install Flask gunicorn
RUN pip install pydot
RUN pip install pandas
RUN pip install graphviz

COPY src/ app/
WORKDIR /app

ENV PORT 8080

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 app:app


These are in Dockerfile

**Comment by Godricly** [comment] 2022-12-29 09:01
Did you fixed it? I got same error on a remote server, I guess its related to the GUI stuff.

**Comment by jamesbraza** [comment] 2024-06-06 18:48
Seems like a dupe of https://github.com/pydot/pydot/issues/257

**Comment by lkk7** [comment] 2024-06-07 19:40
Thanks for the reminder! Closing as duplicate

**Closed by lkk7** 2024-06-07 19:40 UTC
