### ISSUE TITLE
TypeError in parsing dot file

### ISSUE THREAD

**Issue by SHuang-Broad** [pydot/pydot#269] opened 2021-06-30 17:03 UTC
Hi,

I'm looking to display a graph of our genomics pipeline, which can be displayed statically.
However when I tested with pydot, I'm seeing the following error.
Could you please help?

Thanks!
Steve
[PBFlowcell.wdl.dot.zip](https://github.com/pydot/pydot/files/6742703/PBFlowcell.wdl.dot.zip)

The stack trace is pasted below, and the dot file is attached

```

---------------------------------------------------------------------------
ParseException                            Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/dot_parser.py in parse_dot_data(s)
    547         graphparser.parseWithTabs()
--> 548         tokens = graphparser.parseString(s)
    549         return list(tokens)

~/anaconda3/lib/python3.7/site-packages/pyparsing.py in parseString(self, instring, parseAll)
   1954                     exc.__traceback__ = self._trim_traceback(exc.__traceback__)
-> 1955                 raise exc
   1956         else:

~/anaconda3/lib/python3.7/site-packages/pyparsing.py in parseImpl(self, instring, loc, doActions)
   2898             return loc + 1, self.match
-> 2899         raise ParseException(instring, loc, self.errmsg, self)
   2900 

ParseException: Expected "}", found '['  (at char 2257), (line:49, col:27)

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-2-1e0a6f9a2cdf> in <module>
----> 1 graphs = pydot.graph_from_dot_file("PBFlowcell.wdl.dot")

~/anaconda3/lib/python3.7/site-packages/pydot.py in graph_from_dot_file(path, encoding)
    297     if not PY3:
    298         s = unicode(s)
--> 299     graphs = graph_from_dot_data(s)
    300     return graphs
    301 

~/anaconda3/lib/python3.7/site-packages/pydot.py in graph_from_dot_data(s)
    280     @rtype: `list` of `pydot.Dot`
    281     """
--> 282     return dot_parser.parse_dot_data(s)
    283 
    284 

~/anaconda3/lib/python3.7/site-packages/dot_parser.py in parse_dot_data(s)
    552             err.line +
    553             " "*(err.column-1) + "^" +
--> 554             err)
    555         return None

TypeError: can only concatenate str (not "ParseException") to str
```

**Comment by SHuang-Broad** [comment] 2021-06-30 17:04
Sorry I forgot to mention the environment:

```
Python  3.7.7
conda   4.10.1
pydot   1.4.1
```

**Comment by peternowee** [comment] 2021-06-30 18:23
The `TypeError` can be solved by upgrading to pydot 1.4.2 (solved by pydot/pydot#227). It is available in the conda-forge repository: https://anaconda.org/conda-forge/pydot/files. Anaconda's main repo is still offering pydot 1.4.1 on https://anaconda.org/anaconda/pydot/files.

More important is the `ParseException` that is shown halfway through the output. It says `Expected "}", found '['`, which is the same message as in pydot/pydot#235, where the problem was with a hash/pound sign/number sign (`#`) following an HTML tag. See the example there. Perhaps your case is similar.

The `ParseException` further says it failed at `line:49, col:27`, so you could start by looking there, but the actual cause of the problem could be elsewhere on the same line or elsewhere in the DOT file. If there is no obvious problem, try removing parts of the DOT file until the error disappears and then bring back parts of what you last removed to see when the error re-appears. Go back and forth like that until you have a minimal reproducible example (MRE) containing only the part that is causing the error.

Other known parser bugs are in https://github.com/pydot/pydot/issues?q=sort%3Aupdated-desc+label%3Aparser+label%3Abug+expected+found . If you think you found a new bug or need more help, please provide the minimal reproducible example as plain text DOT. I did not open the ZIP attachment.

**Comment by SHuang-Broad** [comment] 2021-06-30 19:02
Thanks for the explanation! 
The line mentioned in the exception message is

```
CALL_PerFlowcellMetrics [label="PerFlowcellMetrics";shape="oval";peripheries=2]
```
which does not have `#` but does have a `;`. 

Removing that line (and links to it) does solve the problem.

**Comment by peternowee** [comment] 2021-06-30 20:36
Ok, thank you. I see this is a duplicate of https://github.com/pydot/pydot/issues/171#issuecomment-871704673. See there for a workaround and please post any replies there as well. Closing this issue as duplicate now. Thanks for reporting.

**Closed by peternowee** 2021-06-30 20:36 UTC
Labels: bug, duplicate, parser
