### ISSUE TITLE
PyDot does not quote attributes containing colons

### ISSUE THREAD

**Issue by julianfortune** [pydot/pydot#264] opened 2021-05-20 01:35 UTC
I noticed a bug where using a colon (`:`) in an edge label caused a crash. I was able to fix it by escaping the colon with a blackslash: `\:`.

Here was the error I received:
```
"dot" with args ['-Tpng', '/tmp/tmph0iza0_n'] returned code: 1

stdout, stderr:
 b''
b"Error: /tmp/tmph0iza0_n: syntax error in line 9 near ':'\n"
```

**Comment by peternowee** [comment] 2021-05-20 16:08
Hi @julianfortune, thanks for taking to effort to report this. I wonder if we could consider this another manifestation of one of the following issues:

- pydot/pydot#224 (Colon in Node names and edges)
- pydot/pydot#118 (Automatically quote node names containing a colon)

Without more information on your input or output it is hard to tell.

If you have time, maybe you could check out those issues and if one of them fits your case, add your suggested workaround of using `\:` there and close this issue pydot/pydot#264.

If you are not sure or if you think your issue is different, please provide a minimal reproducible example and more of the output. Normally pydot should also print the Graphviz output `stdout, stderr:` before the `AssertionError`. See https://github.com/pydot/pydot/issues/203#issuecomment-533164709 for tips on how to gather more information.

Hope to hear from you, thanks for your interest.

**Comment by julianfortune** [comment] 2021-05-20 21:06
Thank you @peternowee; I don't 100% understand what those issues are talking about, so I cannot say for certain that they are the same issue, although they certainly sound related. I will work on the information that you asked for.

Is it feasible to add some 'sanitizing' to escape special characters (in the `Dot` language) in label attributes to improve the user experience? It is not a great experience to encounter an opaque error when using standard ascii characters in a string for a label, but I see that this may have consideration for backwards compatibility.

**Comment by julianfortune** [comment] 2021-05-20 21:56
Okay here is the reproducible example:

### Example Code

```python 
import pydot

def create_graph(label: str):
    graph = pydot.Dot('finite_state_machine', graph_type='digraph', rankdir='LR')

    # Add nodes
    graph.add_node(pydot.Node('0', shape='circle'))
    graph.add_node(pydot.Node('1', shape='doublecircle'))

    # Add edges
    graph.add_edge(pydot.Edge(0, 1, label=label))  # <- This is where the problem is occuring

    print(graph.to_string())
    graph.write_png('output.png')
```

### Bad Path

If I call this on a label that has a colon:

```python
create_graph("a:b")
```

It fails:

```bash
"dot" with args ['-Tpng', '/tmp/tmpqd2ls604'] returned code: 1

stdout, stderr:
 b''
b"Error: /tmp/tmpqd2ls604: syntax error in line 5 near ':'\n"

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    create_graph("a:b")
  File "test.py", line 14, in create_graph
    graph.write_png('output.png')
  File "...pydot.py", line 1743, in new_method
    self.write(
  File "...pydot.py", line 1828, in write
    s = self.create(prog, format, encoding=encoding)
  File "...pydot.py", line 1956, in create
    assert process.returncode == 0, (
AssertionError: "dot" with args ['-Tpng', '/tmp/tmpqd2ls604'] returned code: 1
```

And the debug printout shows the problem:

```python
digraph finite_state_machine {
    rankdir=LR;
    0 [shape=circle];
    1 [shape=doublecircle];
    0 -> 1  [label=a:b]; 
}
```

Note the lack of quotes around `a:b` in `label=a:b`.

### Happy Path

When any sort of slash (`/`, `\`) *anywhere* in the label, there *are* quotes.

If I call this on a label that has a colon *and* a slash:

```python
create_graph("a:b/3.4")
```

It succeeds, and we can see the label is quoted correctly:

```python
digraph finite_state_machine {
    rankdir=LR;
    0 [shape=circle];
    1 [shape=doublecircle];
    0 -> 1  [label="a:b/3.4"]; 
}
```

**Comment by julianfortune** [comment] 2021-05-20 22:03
It looks like this may be a duplicate of #118 (Automatically quote node names containing a colon), but I am not seeing any part of the label attribute being removed as seems to be the case in that issue.

**Comment by julianfortune** [comment] 2021-05-20 22:04
This is issue is a duplicate of #258.

**Comment by peternowee** [comment] 2021-05-20 22:36
Yeah, the reason pydot does not add quotes to `a:b` is that attribute values are IDs according to the DOT Language definition, just as node or edge names are IDs. It then considers `b` to possibly be a compass/port inside the ID, as they are used in the endpoints of DOT edges, even though attribute values of course do not have a compass/port.

Indeed, because we are talking about attribute values here, we are talking about an exact duplicate of pydot/pydot#258. I see you mention while I am typing this. :smile: Not sure what you mean with Dot keywords, but as far as I can tell that is not the root cause of either that issue or the issue here. I consider pydot/pydot#258 a further duplicate of pydot/pydot#118 and pydot/pydot#224 in that they will probably all be solved in one go.

About your question of improving the user experience: The usual suggestion until now has always been to do additional quoting. That is: Wrap the name/attribute/value/ID in additional double quotes. See https://github.com/pydot/pydot/issues/28#issuecomment-92396615 or https://github.com/pydot/pydot/issues/38#issuecomment-92396729: `'"Testnode:###@"'` for some of the earliest suggestions for that. A recent example is in https://github.com/pydot/pydot/issues/258#issuecomment-795798099: `fillcolor='"red:yellow"'`.

But even that is not very user friendly and therefore I think we should have a better solution in pydot 2.0. See the discussions about colons, quoting, ports and new method signatures in pydot/pydot#118 and pydot/pydot#224, but also in pydot/pydot#72. No need to repeat all that here. A first proposal has been made in pydot/pydot#259, but still requires a lot of work. I have some personal notes on it already, but I have not gotten around to writing up a complete response. I also wanted to take a step back and think about the method signatures, transition for existing users, etc. Not ask the contributor for improvements on details first and then have to ask for a larger overhaul again later.

So subscribe to pydot/pydot#259 and the other issues mentioned above if you are interested in the future, better solution and until then I am afraid it will just be additional double-quoting, or backslashes as you found.

I was typing this answer while your comments were coming in, so apologies if it is a bit messy. I will go to sleep now, it is past midnight here already. Will see your reply in the morning. Good luck.

**Closed** 2021-05-21 07:36 UTC
Labels: bug, dot-language, duplicate, quoting
