### ISSUE TITLE
Writing a png a long time but still no output

### ISSUE THREAD

**Issue by liusy58** [pydot/pydot#290] opened 2022-09-26 11:50 UTC
Hi, I am using `graph.write_png(new_file_name)` to generate a png from the dot file. But after quite a long time, The program is still running and I don't got the output. Any help?

My dot file is attached below:
[syscall__execve.txt](https://github.com/pydot/pydot/files/9645916/syscall__execve.txt)

**Comment by lkk7** [comment] 2024-06-08 19:17
Apologies for a late answer (you probably don't need it anymore) – this project was abandoned but it's being slowly resurrected now. 

Your graph is so big that even `dot` itself hangs up on it 😄 
However, I can agree that pydot can be slow, so I'm closing this issue as a duplicate of https://github.com/pydot/pydot/issues/183

**Closed** 2024-06-08 19:18 UTC
