### ISSUE TITLE
nx_pydot.graphviz_layout(G, prog='dot') does not accept nodes with spaces

### ISSUE THREAD

**Issue by Shamalau** [pydot/pydot#399] opened 2024-08-02 14:22 UTC
When switching to the new version of pydot==3.0.1, I noticed a change of behaviour of this part of my code : <br>
`pos = nx.nx_pydot.graphviz_layout(G, prog='dot')` where G is a simple nx.MultiDiGraph. <br>Instead of returning me the pos, it returned me this error : `line 263, in graphviz_layout
    return pydot_layout(G=G, prog=prog, root=root) > line 339, in pydot_layout
    node = node[0]
IndexError: list index out of range`.<br> I noticed that it only happened when one of my MultiDiGraph node was named with a space inside. I'm not sure it is a normal behaviour but I'm posting this here in case it is not.

**Comment by lkk7** [comment] 2024-08-02 16:59
Hi @Shamalau,
Thanks for reporting.
This is probably a duplicate of #396 so I'm closing it for now.
Feel free to post anything in that issue and sorry for the trouble.

**Closed by lkk7** 2024-08-02 16:59 UTC
