### ISSUE TITLE
Problem with graph.write.png...AssertionError: 1

### ISSUE THREAD

**Issue by marcorusc** [pydot/pydot#203] opened 2018-12-14 18:17 UTC
So i'm running this code and it tells me that there is a certain syntax error in /tmp/tmpgIPxNG
Something is not working when i tried to generate the graph... this is the error i have:
-------------------------------------------------------------------------------------------------------------------------------
/usr/bin/python2.7 /home/marco/PycharmProjects/AIforvideogame/Treeplottry.py
"dot" with args ['-Tpng', '/tmp/tmpgIPxNG'] returned code: 1

stdout, stderr:
 
Traceback (most recent call last):
Error: /tmp/tmpgIPxNG: syntax error in line 2 near '>'

  File "/home/marco/PycharmProjects/AIforvideogame/Treeplottry.py", line 23, in <module>

    treeplot.generateDiagram(root, childNode)
  File "/home/marco/PycharmProjects/AIforvideogame/Treeplot.py", line 58, in generateDiagram
    self.graph.write_png('graph.png')
  File "/home/marco/.local/lib/python2.7/site-packages/pydot.py", line 1734, in new_method
    encoding=encoding)
  File "/home/marco/.local/lib/python2.7/site-packages/pydot.py", line 1817, in write
    s = self.create(prog, format, encoding=encoding)
  File "/home/marco/.local/lib/python2.7/site-packages/pydot.py", line 1945, in create
    assert process.returncode == 0, process.returncode
AssertionError: 1

Process finished with exit code 1
-----------------------------------------------------------------------------------------------------------------
I wrote this method:
---------------------------------------------------------------------------------------------------------------------
    def generateDiagram(self, rootNode, currentNode):

        # this method generetes diagram

        # add nodes to edges to graph
        self.createGraph(rootNode, currentNode)
-----------------------------------------------------------------------------------------------------
Honestly I don't know what to do anymore....

**Comment by prmtl** [comment] 2018-12-15 21:59
From the error, I cannot see more that there might be a problem with generated DOT string that is passed to `dot` program to render a graph.

It would be extremely helpful to see full code that generate graph or the resulting DOT string (it can be checked by printing results of `some_graph.to_string()`)

**Comment by marcorusc** [comment] 2019-01-08 09:41
> From the error, I cannot see more that there might be a problem with generated DOT string that is passed to `dot` program to render a graph.
> 
Ok thanks for the help! here is the code:
 def generateDiagram(self, rootNode, currentNode):

        # this method generetes diagram

        # add nodes to edges to graph
        self.createGraph(rootNode, currentNode)

        f = pl.figure()
        f.add_subplot(1, 2, 1)
        # show search tree
        self.graph.write_png('graph.png')
        img = mpimg.imread('read.png')
        pl.imshow(img)
        pl.imshow('tight')
        pl.axis('off')

        f.add_subplot(1, 2, 2)
        # show state image
        pl.imshow(currentNode.state.drawState())
        pl.axis('tight')
        pl.axis('off')
        font = {'family': 'serif',
                'color': 'white',
                'weight': 'normal',
                'size': 20,
                }
        for variable in CSP.variables:
            # get average positions
            avgx = 0
            avgy = 0
            for (posx, posy) in CSP.positions[variable]:
                avgx += posx
                avgy += posy
            avgx /= len(CSP.positions[variable])
            avgy /= len(CSP.positions[variable])
            plt.text(avgy - 0.3, avgx, variable, fontdict=font)

        mng = plt.get_current_fig_manager()
        mng.window.state('zoomed')
        plt.axis('tight')
        plt.axis('off')
        plt.show()

**Comment by reox** [comment] 2019-01-10 09:23
This looks to be a similar bug: https://github.com/androguard/androguard/issues/584

See this comment: https://github.com/androguard/androguard/issues/584#issuecomment-451367975
```
Traceback (most recent call last):
  File "C:\Users\XXX\.windows-build-tools\python27\Scripts\androdd.py", line 175, in <module>
    args.jar, args.decompiler, args.format)
  File "C:\Users\XXX\.windows-build-tools\python27\Scripts\androdd.py", line 109, in export_apps_to_format
    method2format(filename + "." + form, form, None, buff)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\androguard\core\bytecode.py", line 393, in method2format
    getattr(g, "write_" + _format.lower())(output)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\pydot.py", line 1673, in new_method
    encoding=encoding)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\pydot.py", line 1756, in write
    s = self.create(prog, format, encoding=encoding)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\pydot.py", line 1884, in create
    assert p.returncode == 0, p.returncode
AssertionError: 1
```

I tested the very same code with python 3 and 2.7.15 and also 2.7.13, graphviz 2.34 and 2.38 and pydot 1.4.1 but it works for me.
I'm not sure where the problem is in this case, but in the thread are many files included for debugging.

**Comment by peternowee** [comment] 2019-09-19 14:45
I feel that different issues are getting mixed up here in the same GitHub issue, so I will try to disentangle them a bit. First, to prevent further mix-ups, my thoughts on how best to investigate and report this kind of error:

### `AssertionError` from `create`

If you are seeing a traceback ending in:
````
  File "......pydot.py", line ...., in create
    assert p.returncode == 0, p.returncode
AssertionError: .....
````
Then that tells you that the GraphViz executable called by pydot (`dot`, `neato`, etc.) failed. For the rest, it is just too generic. Seeing it does not necessarily mean that you are dealing with the same issue as others seeing the same message.

There can be many reasons why GraphViz failed and trying to discuss all of them in this one, single GitHub issue would, in my opinion, lead to a lot of confusion. So, you need to investigate a bit more.

### Finding the GraphViz error

To find out what problem GraphViz ran into, start by looking at the information it returned. Look above or below the traceback for lines like:
````
"......" with args .................. returned code: ......
stdout, stderr:
......
......
````

In the OP's case:
````
"dot" with args ['-Tpng', '/tmp/tmpgIPxNG'] returned code: 1
stdout, stderr:

Error: /tmp/tmpgIPxNG: syntax error in line 2 near '>'
````

At the top, it shows which GraphViz executable was called and with which arguments. Below `stdout, stderr` is the error that GraphViz reported. In this case, GraphViz complains about the tmp-file. The tmp-file is a text file describing the graph in the DOT language ([Wikipedia][1], [Specification][2]). The tmp-file is written by pydot especially to serve as input for GraphViz.

So, if you see a `syntax error` about a tmp-file, the problem is probably with the DOT string generated by pydot. However, since there are many ways of not complying with the DOT language specification and the GraphViz error message is quite terse and generic, you still cannot always say for sure that you are experiencing the same issue as others seeing a similar message.

### Capturing the DOT string

To better determine your issue, we need to know what DOT string pydot generates. The DOT string usually consists of multiple lines, for example:
````
graph mygraph {
1 [mylabel=myvalue];
}
````
I think it would be very useful if in the future pydot would print the DOT string right along with the GraphViz error. I plan to submit a patch for that soon. For now, though, you need to capture your DOT string yourself and here are two different methods for doing that:

- As mentioned by @prmtl in an earlier comment, you can edit your own source code. Replace your call to `some_graph.write_png()` (or whatever other `write_...`-method you are calling) by `print(some_graph.to_string())`.
- Alternatively, you can prevent the deletion of the tmp-file by commenting out [`os.unlink(tmp_name)` at line 1930 of `pydot.py`][3] (pydot 1.4.1).

In case you are really not able to get hold of the DOT string, supply your source code instead (see below).

Once you have your DOT string, you can test if you got the right one (the one that caused the error) by saving it in a text file (e.g. `offending-dot-string.dot`) and manually running it through the GraphViz executable. The program and arguments to use were in the error message above. Add the `-O` option to have any resulting images written to a file. For example:

    $ dot -Tpng -O offending-dot-string.dot 

This should result in the same error as before.

The DOT string should be part of your bug report or support question. If it is very long because of repetitive parts, try removing those from your source code or source input, while keeping the minimal parts necessary to reproduce the GraphViz error.

Optionally, you can already try to compare your DOT string with [the DOT language specification][2] yourself to see if you can find out where it does not comply. For example, labels or values might be missing double quotes, contain special characters or use reserved names. Knowing the exact cause, you can check the [pydot issue list][4] for existing issues.

When adding your comments to an existing issue, make sure you are having the exact same issue. Otherwise, consider opening a new issue first. You can always create a link with a possibly related, earlier issue by mentioning it in your new issue.

### Supplying your source code

Supplying some of your source code is often useful, especially if you were unable to supply your DOT string. Your source code will help to determine how pydot created the offending part of the DOT string. When supplying your source code, try to cut it down to a [Minimal Working Example][5]. Remove as much code and dependencies as you can, while making sure it can still reproduce the issue. Make sure your code is self-contained, i.e. it can run by itself.

Try to format all your error messages, DOT strings and source code as `code`. Check the [GitHub Mastering Markdown guide][6] on how to do that and use the Preview to check if you succeeded.

### Summary

To summarize, my suggestions:
- `AssertionError` from `create` can have many causes. Investigate more before choosing between adding your comments to an existing issue or opening a new issue.
- What error code and error message did GraphViz report (above or below traceback)?
- In case that error message complains about the tmp-file, especially with `syntax error in line`, try to provide the DOT string.
- If you provide your source code, keep it short and self-contained.

Note that I am not the maintainer of this project, so these are no more than just my suggestions, after seeing that this discussion thread had gotten a bit convoluted.

### Individual responses

@marcorusc 
I reduced the source code you supplied to the following minimal working example:
````
#!/usr/bin/env python3

import pydot

G = pydot.Dot(graph_type='graph', dpi=300)
N = pydot.Node(u'0', shape="plaintext", label="<<table>><tr>"
               "<td bgcolor= '#FF0000'>&nbsp;</td></tr></table>>")
G.add_node(N)
print(G.to_string())
G.write_png('graph.png', prog=['dot'])
````
And this is the DOT string generated by the above code:
````
graph G {
dpi=300;
0 [label=<<table>><tr><td bgcolor= '#FF0000'>&nbsp;</td></tr></table>>, shape=plaintext];
}
````
The above code reproduces the error message you saw. It also makes the cause easy to spot: The double closing brackets in `<<table>>`, which were also in your code. After changing that to `<<table>`, the error is gone and the image gets written correctly.

@reox 
Your error message also indicates a problem with the DOT string created by pydot, but the `syntax error` line does not mention `near '>'`, so is probably different from the issue the OP was seeing. Judging by the discussion you linked to (androguard/androguard#584), it seems you found another probable cause for the error? If you still suspect a bug in pydot, please consider opening a new issue for that and supplying the DOT string and minimal source code as described above.

@hoverjmt
You created PR pydot/pydot#208 (_propagate 'SYSTEMROOT' when calling GraphViz_) and linked it to this issue. However, judging by your comment there that your PR solves a Windows-specific issue and by the DOT string-related error messages reported by the other two reporters here, I suspect that the underlying issue that you solved with your PR was very different from theirs. If you still have the GraphViz error that you got (shown above or below the traceback), perhaps you could add that as a comment to your PR, or provide some more explanation in the commit message. Other than that, because I do not use Windows, I cannot really say much about the actual change you propose. Hopefully, it will get reviewed soon.

Thanks and good luck, everybody!

### Versions

python 3.7.3, pydot 1.4.1, chardet 3.0.4, pip 19.2.3, pyparsing 2.4.2, setuptools 41.2.0, wheel 0.33.6, Debian 10.1, GraphViz 2.40.1-6.

[1]: https://en.wikipedia.org/wiki/DOT_(graph_description_language)
[2]: https://graphviz.gitlab.io/_pages/doc/info/lang.html
[3]: https://github.com/pydot/pydot/blob/v1.4.1/pydot.py#L1930
[4]: https://github.com/pydot/pydot/issues
[5]: https://en.wikipedia.org/wiki/Minimal_working_example
[6]: https://guides.github.com/features/mastering-markdown/

**Comment by reox** [comment] 2019-09-19 21:10
@peternowee thanks for looking more into this. 
Unfortunately, I could never reproduce the issue which was reported in androguard. It looked like, that is was some incompatability between graphviz and pydot and or the generated dot code.
There is some stuff uploaded here https://github.com/androguard/androguard/issues/584#issuecomment-453000537
Back then, I tried to compile all the supplied dot files with the `dot` command and got no error.
I even tried today, and all the dot files happily compile with graphviz version 2.40.1 (20161225.0304).
The only thing I could not test was Windows 10, which I dont have at hand.
So _maybe_ this is a problem of dot on windows 10? But as the issuer opener never wrote back, I will probably close the issue in the androguard tracker as not-reproducible.

**Comment by peternowee** [comment] 2019-09-21 03:09
@reox

> Unfortunately, I could never reproduce the issue which was reported in androguard. It looked like, that is was some incompatability between graphviz and pydot and or the generated dot code.
There is some stuff uploaded here https://github.com/androguard/androguard/issues/584#issuecomment-453000537

Ok, so from that upload I had a look at `outimgdottest.zip` and `testdot.txt`. The ZIP-file unpacks to a huge directory tree with each folder containing one or more pairs of `.dot` and `.ag` files. If I understand correctly, this directory tree was created by your software, which uses pydot to create the `.dot` files (or other formats such as `.jpg`). `testdot.txt` contains the console output of your program while it was creating the tree.

The console output has two main parts: First, many `Dump ....` lines that seem to report the creation of the hundreds of `.dot` file and the `.ag` (bytecode) files. For the first 1841 lines, everything is fine, but on line 1842 pydot suddenly reports an error:

````
testdot.txt:1840: Dump Landroid/support/v4/app/FragmentManagerImpl; restoreAllState (Landroid/os/Parcelable; Ljava/util/ArrayList;)V ... dot ... bytecodes ... 
testdot.txt:1841: Dump Landroid/support/v4/app/FragmentManagerImpl; retainNonConfig ()Ljava/util/ArrayList; ... dot ... bytecodes ... 
testdot.txt:1842: Dump Landroid/support/v4/app/FragmentManagerImpl; saveAllState ()Landroid/os/Parcelable; ... dot ... "dot" with args ['-Tdot', 'c:\\users\\mxai064\\appdata\\local\\temp\\tmpqywuqn'] returned code: 1
````
`"dot" with args` marks the beginning of the second part of the console output, the part generated by pydot.
````
testdot.txt:1843: 
testdot.txt:1844: stdout, stderr:
testdot.txt:1845:  digraph G {
[... Lines 1845-3341 contain the GraphViz output DOT string ...]
testdot.txt:3341: }
testdot.txt:3342: 
testdot.txt:3343: 
testdot.txt:3344: Error: syntax error in line 8 
testdot.txt:3345: 
testdot.txt:3346: ... 
testdot.txt:3347: 
testdot.txt:3348: <TR> ...
testdot.txt:3349: 
testdot.txt:3350: in label of node struct_c33832c378a1dacc5d6cf2a69ecc489b
testdot.txt:3351: 
testdot.txt:3352: Warning: node struct_c33832c378a1dacc5d6cf2a69ecc489b, port header unrecognized
testdot.txt:3353: 
testdot.txt:3354: Warning: node struct_c33832c378a1dacc5d6cf2a69ecc489b, port tail unrecognized
````
The error message in lines 3344-3354 originated from GraphViz.

> Back then, I tried to compile all the supplied dot files with the `dot` command and got no error.
> I even tried today, and all the dot files happily compile with graphviz version 2.40.1 (20161225.0304).

Do you mean all the ones from the ZIP archive? You do realize that it misses the crucial DOT file for `android/support/v4/app/FragmentManagerImpl; saveAllState ()Landroid/os/Parcelable;`, right? The console log shows that the error was raised at that point as well.

Luckily, in this case, even though it reported an error, GraphViz was somehow still able to write its output DOT string for `saveAllState` to standard output (`stdout`), which pydot then printed before raising the error. It is in `testdot.txt` lines 1845-3341. I saved it to a separate file and then manually fed it to `dot`. For me, on Linux, that resulted in the same error message:

````
$ dot -Tjpg -O failing-saveAllState.dot 
Error: syntax error in line 15 
... 

<TR> ...
in label of node struct_c33832c378a1dacc5d6cf2a69ecc489b
Warning: node struct_c33832c378a1dacc5d6cf2a69ecc489b, port header unrecognized
Warning: node struct_c33832c378a1dacc5d6cf2a69ecc489b, port tail unrecognized
````
I then took a good look at that `struct_c33832c378a1dacc5d6cf2a69ecc489b` in the DOT string. Deleting the HTML rows between the header and tail made the error disappear. Some further trial and error led to the offending line:

    testdot.txt:3009: <TR><TD ALIGN="LEFT" BGCOLOR="lightgray"> <FONT FACE="Times-Bold" color="blue">2b8</FONT> </TD><TD ALIGN="LEFT" BGCOLOR="lightgray"> <FONT FACE="Times-Bold" color="black">const-string </FONT> <FONT color="#6D6DDF">v11</FONT>, <FONT color="red"><br/>u'saveAllState: adding fragment<br/>

A similar line in `struct_8261ee0e4a17acb444d73360286645be` that does not cause any problems:

    testdot.txt:3255: <TR><TD ALIGN="LEFT" BGCOLOR="lightgray"> <FONT FACE="Times-Bold" color="blue">356</FONT> </TD><TD ALIGN="LEFT" BGCOLOR="lightgray"> <FONT FACE="Times-Bold" color="black">const-string </FONT> <FONT color="#6D6DDF">v11</FONT>, <FONT color="red"><br/>u'saveAllState: adding back<br/>stack #'</FONT> </TD></TR>

As you can see, there are some closing tags missing at the end of line 3009. All the surrounding lines end in `</FONT> </TD></TR>`. Also, the `u'` looks like a Python-like string, but the closing quote (`'`) is missing. The omission of that `'` probably does not matter very much, because it is just part of some inner-HTML text now, but still it might be a clue. I tested that adding the HTML closing tags `</FONT> </TD></TR>` is necessary and enough to make the error go away.

(Used versions: python 3.7.3, pydot 1.4.1, chardet 3.0.4, pip 19.2.3, pyparsing 2.4.2, setuptools 41.2.0, wheel 0.33.6, Debian 10.1, GraphViz 2.40.1-6.)

So, there may be something special about `android/support/v4/app/FragmentManagerImpl; saveAllState ()Landroid/os/Parcelable;`, `struct_c33832c378a1dacc5d6cf2a69ecc489b`, `2b8` that triggers a bug in the code to create a DOT string containing broken HTML.

Now the question becomes: In what code? Where exactly was that DOT string with broken HTML-line created? This question is not easy to answer, because in the process of creating a `dot` output, three different DOT files get created:

1. Androguard's `androdd.py`, in [method `method2format()` of `bytecode.py`](https://github.com/androguard/androguard/blob/v3.3.5/androguard/core/bytecode.py#L357) builds the first DOT string itself, correct? It sends its DOT string to pydot as an argument in a call to `pydot's graph_from_dot_data()` function.
2. pydot's [`graph_from_dot_data()` function](https://github.com/pydot/pydot/blob/v1.4.1/pydot.py#L273) reads the DOT string received from Androguard and creates a Dot object of it, which it then returns to Androguard. Androguard, still in `method2format()`, then calls one of pydot's `write_...()` methods, such as `write_jpg()` or in this case `write_dot()`, which, after some loops and twists, asks [`Graph.to_string()`](https://github.com/pydot/pydot/blob/v1.4.1/pydot.py#L1471) to generate the DOT string for the tmp-file for GraphViz. Note that the input and output DOT strings may differ, even if no changes were requested. For example, the output side seems not fully compliant with the DOT language specification with regard to quoting. The output DOT string can be captured by [commenting out the deletion of the tmp-file](https://github.com/pydot/pydot/blob/v1.4.1/pydot.py#L1930).
3. The GraphViz executable, reads the tmp-file (DOT string) from pydot. If it finds a mistake in it, it will return an error, regardless of the requested output format. It seems that if the error is not too serious, it will still generate the requested output as well. If the requested output format is `dot`, it will output a DOT string, either to stdout or to the requested file. Here as well, the input and output DOT strings may differ, more significantly even than in step 2.

For the issue we are discussing here:
1. We do not have the DOT string output of step 1 (Androguard). Can you say if it was built from `raw` or `method2dot(mx)` in this case?
2. We also do not have the DOT string output of step 2 (pydot). The error message from GraphViz tells us that it was broken already as well, and in the same place (`struct_c33832...`), but we do not know if it was broken in exactly the same way.
3. We only have the DOT string output of step 3 (GraphViz), as shown in `testdot.txt` lines 1845-3341, which has broken HTML because of missing HTML closing tags (see above).

Just for testing, I took the broken DOT string from the GraphViz output (step 3) and fed it back to pydot (step 2). Not only did the pydot input parser not complain at any point, the DOT string that pydot wrote as output was broken again. This means that:
- Depending on the expectations that one may have of pydot regarding strictness and DOT language compliance, the acceptance and even writing of non-conforming DOT strings without any warning, as shown here, may be considered bugs of pydot. (GraphViz also outputs a broken DOT string on broken input, but at least it gives a big warning and returns an exit code indicating failure.)
- We yet cannot exclude the possibility that the output your program (step 1) was broken already as well (because the pydot parser would not have complained about it if it was).

> The only thing I could not test was Windows 10, which I dont have at hand.
> So _maybe_ this is a problem of dot on windows 10?

I do not use Windows at all, but here are some of the Windows-specific pydot issues that I am aware of:
- Issues with finding the GraphViz programs under Anaconda on Windows. But that does not seem to be the problem here.
- I have seen mysteriously inconsistent GraphViz output on AppVeyor running Windows. See pydot/pydot#213.
- The SYSTEMROOT patch in pydot/pydot#208. It is not clear yet exactly what error that user was seeing, but he says his patch solved it, so it's worth the try.

> But as the issuer opener never wrote back, I will probably close the issue in the androguard tracker as not-reproducible.

Yeah, I don't know, that's up to you. You might first ask him if he is still seeing this issue and if so, point him to this discussion.

You might also consider wrapping the calls to pydot in your program (lines [389](https://github.com/androguard/androguard/blob/v3.3.5/androguard/core/bytecode.py#L389) and [392 of bytecode.py](https://github.com/androguard/androguard/blob/v3.3.5/androguard/core/bytecode.py#L392)) in `try... except` statements, and then in the `except` block let your program print out variable `buff` containing the DOT string it generated. That might help any future debugging.

On the pydot side, at least the test I did above brought out a situation where pydot first accepts and then writes non-conformant DOT strings, both without even a warning. This might merit the creation of one or two separate issues here, if this has not already been discussed earlier. A minimal working example should be produced and the issue list checked for earlier mentions. I have seen other situations where pydot fails to follow the [DOT language specification](https://www.graphviz.org/doc/info/lang.html) exactly, so a general discussion might need to be started about that as well. Of course, my time is limited, so others are free to pick this is up if I don't do it.

Thanks!

**Comment by reox** [comment] 2019-09-21 12:14
@peternowee okay you went far down the rabbit hole ;)

> You do realize that it misses the crucial DOT file for android/support/v4/app/FragmentManagerImpl; saveAllState ()Landroid/os/Parcelable;, right

d'oh. If you look in the androguard's issue, that is exactly the method I also found breaking...
But again, I do not remember that it would fail in my setup, although I do not had the APKs the issue opener used. But as he said, that it would fail everywhere, I concluded it would fail whenever this mehtod is present (it is a method from the android support library, which is a library added to almost every APK file)


> We do not have the DOT string output of step 1 (Androguard). Can you say if it was built from raw or method2dot(mx) in this case?

It was build from `method2dot`. I took some random APK and filtered for the saveAllState method.
method2dot returns a `dict`, so this is the dict as JSON: 
[saveAllState.method2dot.txt](https://github.com/pydot/pydot/files/3638576/saveAllState.method2dot.txt)



> We also do not have the DOT string output of step 2 (pydot). The error message from GraphViz tells us that it was broken already as well, and in the same place (struct_c33832...), but we do not know if it was broken in exactly the same way.

So this is the buffer just before pydot.graph_from_dot_data is called: 
[saveAllState.before_pydot.txt](https://github.com/pydot/pydot/files/3638578/saveAllState.before_pydot.txt)

Calling `graph_from_dot_data` works fine for me. But when I call the `write_dot` method, I get this error:
```
"dot" with args ['-Tdot', '/tmp/tmpinu6j3kg'] returned code: 1

stdout, stderr:
 b'digraph G { <SNIP ....>
n}\n'
b'Error: syntax error in line 8 \n... \n<TR> ...\nin label of node struct_b471bb419b65bdad3b2d5e996e9d4580\nWarning: node struct_b471bb419b65bdad3b2d5e996e9d4580, port header unrecognized\nWarning: node struct_b471bb419b65bdad3b2d5e996e9d4580, port tail unrecognized\n'

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
~/git/androguard/androguard/cli/main.py in <module>
----> 1 x.write_dot('saveAllState.write_dot.txt')

~/git/androguard/venv/lib/python3.7/site-packages/pydot.py in new_method(path, f, prog, encoding)
   1732                 self.write(
   1733                     path, format=f, prog=prog,
-> 1734                     encoding=encoding)
   1735             name = 'write_{fmt}'.format(fmt=frmt)
   1736             self.__setattr__(name, new_method)

~/git/androguard/venv/lib/python3.7/site-packages/pydot.py in write(self, path, prog, format, encoding)
   1815                 f.write(s)
   1816         else:
-> 1817             s = self.create(prog, format, encoding=encoding)
   1818             with io.open(path, mode='wb') as f:
   1819                 f.write(s)

~/git/androguard/venv/lib/python3.7/site-packages/pydot.py in create(self, prog, format, encoding)
   1943             print(message)
   1944 
-> 1945         assert process.returncode == 0, process.returncode
   1946 
   1947         return stdout_data

AssertionError: 1
```

So I would assume the problem is somewhere in `method2dot`, creating broken code.
Btw it is quite a messy method, and I don't like the design that it creates html code by appending strings. I'll look into this more, where the error comes from.

**Comment by peternowee** [comment] 2019-09-23 14:52
> @peternowee okay you went far down the rabbit hole ;)

Haha, yes, that was quite the journey! :) But, very rewarding, seeing how much progress we have made in just a few back-and-forths. Thank you for responding so quickly and with new information. Really very helpful!

> > We do not have the DOT string output of step 1 (Androguard). Can you say if it was built from raw or method2dot(mx) in this case?
> 
> It was build from `method2dot`. I took some random APK and filtered for the saveAllState method.
> method2dot returns a `dict`, so this is the dict as JSON:
> [saveAllState.method2dot.txt](https://github.com/pydot/pydot/files/3638576/saveAllState.method2dot.txt)
> 
> > We also do not have the DOT string output of step 2 (pydot). The error message from GraphViz tells us that it was broken already as well, and in the same place (struct_c33832...), but we do not know if it was broken in exactly the same way.
> 
> So this is the buffer just before pydot.graph_from_dot_data is called:
> [saveAllState.before_pydot.txt](https://github.com/pydot/pydot/files/3638578/saveAllState.before_pydot.txt)

Yes, OK, so if the DOT string in that last file was in the buffer of your program, then that is the output of step 1 (AndroGuard) and input for step 2 (pydot). With some trial and error, I found that this is the line that confuses pydot:

    <TR><TD ALIGN="LEFT" BGCOLOR="lightgray"> <FONT FACE="Times-Bold" color="blue">32c</FONT> </TD><TD ALIGN="LEFT" BGCOLOR="lightgray"> <FONT FACE="Times-Bold" color="black">const-string </FONT> <FONT color="#7777BB">v7</FONT>, <FONT color="red"><br/>saveAllState: adding back stack<br/>#</FONT> </TD></TR>

With it, I can now also generate the DOT string output of step 2 (pydot). In there, the offending line has been cut off, with the hash/pound sign/number sign (`#`) as the first missing character:

    <TR><TD ALIGN="LEFT" BGCOLOR="lightgray"> <FONT FACE="Times-Bold" color="blue">32c</FONT> </TD><TD ALIGN="LEFT" BGCOLOR="lightgray"> <FONT FACE="Times-Bold" color="black">const-string </FONT> <FONT color="#7777BB">v7</FONT>, <FONT color="red"><br/>saveAllState: adding back stack<br/>

Now that the line is missing all its closing tags (`</FONT> </TD></TR>`), it is of course not accepted by GraphViz, leading to the error you reported.

With some more trial and error, I found that the combination of `<BR/>#` causes the pydot parser to ignore the rest of the line, as if `#` had started a comment. Strangely enough, just a `#` without the `<BR/>` right in front of it does not cause any problems.

> So I would assume the problem is somewhere in `method2dot`, creating broken code.

AFAICT, the offending line created by your program is both valid HTML and a valid DOT 'HTML-like' label:

-  `<BR/>` is perfectly allowed, in [XML, HTML](https://stackoverflow.com/questions/1946426/html-5-is-it-br-br-or-br) and [DOT HTML-like labels](https://www.graphviz.org/doc/info/shapes.html#html).
- The pound sign (`#`) is not one of the [characters that need to be escaped in HTML](https://stackoverflow.com/questions/7381974/which-characters-need-to-be-escaped-in-html), nor one of the [characters that need to be escaped in DOT HTML-like labels](https://www.graphviz.org/doc/info/shapes.html#html). And although the DOT Language specification states that [lines beginning with `#` are discarded](https://www.graphviz.org/doc/info/lang.html), the `#` here is clearly not at the beginning of the line. The specification of [DOT HTML-like labels](https://www.graphviz.org/doc/info/shapes.html#html) further makes a statement about HTML comments, but those have a different syntax (`<!-- .... -->`, not `#`).

> Btw it is quite a messy method, and I don't like the design that it creates html code by appending strings. I'll look into this more, where the error comes from.

I don't know, I did not really look at that method anymore now. If you are considering using a third-party library for creating your XML/HTML, note that The DOT Language specification has some special needs:

> As an ID, an HTML string can be any legal XML string. However, if used as a label attribute, it is interpreted specially and must follow the syntax for HTML-like labels. 
> -- [The DOT Language](https://www.graphviz.org/doc/info/lang.html)

> NOTE: The features and syntax supported by these labels are modeled on HTML. However, there are many aspects that are relevant to Graphviz labels that are not in HTML and, conversely, HTML allows various constructs which are meaningless in Graphviz. We will generally refer to these labels as "HTML labels" rather than the cumbersome "HTML-like labels" but the reader is warned that these are not really HTML. The grammar below describes precisely what Graphviz will accept.
> -- [Node Shapes: HTML-Like Labels](https://www.graphviz.org/doc/info/shapes.html#html)

So, make sure that any the third-party XML/HTML library you use is flexible enough to allow for DOT-specific customization.

> Edit: for me it looks like an issue in pydot. If you compile the file directly with dot (so you take the buffer which is passed to pydot.graph_from_dot_data) it works and I can create a png out of it.

Indeed, same findings here. I agree that this is an issue in pydot, maybe even two:

- On the import side, the parser breaks off DOT HTML-like labels containing `<BR/>#`.
- Depending on if this should be expected of pydot, possibly the lack of validation of DOT HTML-like labels at any point (neither at the time it is added to the node, nor at the time it is written to a DOT string).

I already searched for earlier mentions of these problems, also in the pydot-ng issue list, but could not find any. So, I am planning to create these new two issues in the next few days. As always, others may feel free to do it in my place if I take too long.

Thanks again for your help in narrowing this down!

**Comment by reox** [comment] 2019-09-24 05:56
Okay thanks for the information!
One problem might be that the html entity for `#` is `&#35;`, so there is again the hash char involved :D 
I'll test if this works as a workaround.

**Comment by peternowee** [comment] 2019-09-24 06:28
@reox Haha, yes, that's funny. But you are lucky, because `<br/>&#35;` does not trigger the bug in pydot. And GraphViz displays it correctly as `#`, so great workaround, I think. I tried with the HTML5 named reference `&num;` as well, btw: It passes through pydot without damage, but it is not recognized by GraphViz (`undefined entity`).

**Comment by sytelus** [comment] 2020-02-06 07:03
I can reproduce this issue consistently on Windows 10, Python 3.7 with below minimal code:

```
import pydot
g = pydot.Dot()
g.set_type('digraph')
node = pydot.Node('legend')
node.set("shape", 'box')
g.add_node(node)
node.set('label', 'mine')
png = g.create_png()

```

It appears that one of the open PR already resolves this issue. Unfortunately, pydot project seems to be dead with 7 open PRs and no progress for more than a year. So I just forked it and merged 7 open PRs and now everything is working again. Please feel free to submit any PRs on my fork: https://github.com/sytelus/pydot

If you had like to use my fork in your project as a dependency, just include below in your setup.py:
```
    install_requires=[
          'pydot @ git+https://github.com/sytelus/pydot@v1.5.0#egg=pydot'
    ]
```

**Comment by wc411421** [comment] 2020-02-14 07:31
As mentioned with @pauloxnet , the error occurs in the function 'create'. When I trace the function call path,  _create->call_graphviz->get_executable_extension_, I find that the final executed program is not 'dot.exe' but 'dot.bat', and in windows platform the 'dot.bat' does not exist. The problem appears in if-condition, _is_windows_. I modified the code 
to
`
def get_executable_extension():
    # type: () -> str
    if is_windows():
        #return '.bat' if is_anacoda() else '.exe'
        return '.exe'
    else:
        return ''
`
![image](https://user-images.githubusercontent.com/24862284/74509413-61765b00-4f3c-11ea-9f97-861dde59ed94.png)

And it works well for me now.

**Comment by peternowee** [comment] 2020-02-14 08:35
@wc411421 The title of this issue #203 is a very generic error message that can have many causes. I think the specific problem and solution that you describe have an existing discussion in issues #205 (with #210 as a duplicate). Maybe you can post your solution in #205 as well and continue to discuss it there?

**Comment by peternowee** [comment] 2020-08-29 17:32
I assume this issue can be closed now:

- @marcorusc I assume [my comment of 2019-09-19 above](https://github.com/pydot/pydot/issues/203#issuecomment-533164709) answered your question. Otherwise, feel free to reopen this issue.
- @reox As announced in [my comment of 2019-09-23 above](https://github.com/pydot/pydot/issues/203#issuecomment-534135106), I created two new issues for the specific problems that surfaced from your report: pydot/pydot#215 (Validation of HTML strings and HTML-like labels, or lack thereof) and pydot/pydot#235 (Parser breaks off lines at hash symbol following HTML tag). Thank you again for helping investigate your issue.
- @sytelus I have been granted commit rights to this repository and plan to make a 1.4.2 point release soon to fix the most obvious issues, and then work towards a larger release 1.5.0 or 2.0.0. I am not sure which of the PRs solved the issue you were seeing and I cannot reproduce any errors with the example code you provided in [your comment of 2020-02-06 above](https://github.com/pydot/pydot/issues/203#issuecomment-582766169). Perhaps it was Windows/Anaconda-related and then from all the 7 PRs that were open at the time you forked, I think PR pydot/pydot#208 would seem to be the most likely candidate, but as I describe there I would like to see some further confirmation and explanation before I merge that. It would be nice if you could check if it was indeed pydot/pydot#208 that solved your issue and provide more details in that discussion, though I understand it is a bit late now. Other issues that may have caused the error you saw are pydot/pydot#205 and pydot/pydot#207. Or feel free to open a new issue if you find your issue had yet another cause.
- Discussions on improving the finding of the Graphviz executables on Windows/Anaconda (`.bat`/`.exe`-issues) have continued in pydot/pydot#205.
- To anyone else looking for a solution to `AssertionError: 1` or any other `AssertionError: ` code, please note that this is a very generic error message and that it can have many different causes. To find the specific cause of your error with pydot 1.4.x, see the instructions in [my comment of 2019-09-19 above](https://github.com/pydot/pydot/issues/203#issuecomment-533164709), or check out the other comments and links to other issues from here to see if one of those cases is similar to yours. If not, or if you are not sure, feel free to open a new issue.
- Finally, improvements to the way pydot handles Graphviz errors are on the way and that should prevent the confusion that we saw here. These improvements are discussed in pydot/pydot#218 (currently closed, but will be reopened soon) and will probably land in the next major/minor release, so 1.5.0 or 2.0.0.

**Closed** 2020-08-29 17:37 UTC
Labels: bug, dot-language
