### ISSUE TITLE
get_node() and get_edge() does not match correctly if the original name was quoted

### ISSUE THREAD

**Issue by qinyeli** [pydot/pydot#180] opened 2018-07-11 23:51 UTC
To replicate the error:

```python
graph = pydot.Dot()
nodeA = pydot.Node('Node A')
graph.get_node('Node A')  # This return an empty list, whereas it should return [nodeA]
```

This error happens when the original names (given by the user) and the quoted names (used in inner dicts as keys) are mismatched.

**Comment by peternowee** [comment] 2020-08-30 13:12
Still reproducible under current pydot 1.4.1:

```python3
import pydot
graph = pydot.Dot()
nodeA = pydot.Node('Node A')
graph.add_node(nodeA)
graph.get_node('Node A')   # returns: []
graph.get_node('"Node A"')  # returns: [<pydot.Node object at 0x7f08ea413470>]
```

**Comment by peternowee** [comment] 2020-11-28 18:16
@qinyeli This is also in reply to your PR pydot/pydot#181. Sorry your work did not get reviewed earlier. I am actually thinking of solving this issue by having pydot internally store ID names unquoted and, if necessary, store information about quoting style in a separate pydot attribute, starting with pydot 2.0.0. See my comments in the last two paragraphs of https://github.com/pydot/pydot/issues/72#issuecomment-726333844. I assume that, once this new model is in place, changes to `get_edge()` and `get_node()` should not be necessary anymore. At the same time, PR pydot/pydot#181 is also not really suitable for the upcoming pydot 1.4.2 release, because that will just be a bug-fix/point release and probably the last in the pydot 1.x series, so we need to keep the risk of regressions low. So, I am afraid I will be closing your PR, unless you have any comments. Please let me know if want to get involved in implementing the new model I described, though be prepared it will cost a lot more time and effort, as it affects many parts of the code and raises many side questions, some already described in https://github.com/pydot/pydot/issues/72#issuecomment-726333844.

**Comment by openSourcerer9000** [comment] 2021-02-01 14:11
As a workaround, this worked for me:

`def getnode(dott,lbl):
    '''dott: dot object containing node to search for \n
    lbl: node name (str)'''
    nodez =  dott.get_nodes()
    for noad in nodez:
        if noad.obj_dict['attributes']['label'].startswith(r'"{'+lbl+'|'):
            return noad`

This works because all of my nodes are in the format of UML class, you may need to adjust the validation function to taste depending on where your node name is located, I'm not sure. Just make sure it gives you a specific validation, using `lbl in ...` could be problematic if there is another name which includes the name being searched.

**Comment by ferdnyc** [comment] 2024-06-16 06:12
@peternowee wrote:
> I am actually thinking of solving this issue by having pydot internally store ID names unquoted

That's definitely the route I think things should go, because (as was pointed out in #355) the ID is _only_ quoted when it's set in the constructors. If you later call `my_node.set_name("new name")`, the **new** name will be stored unquoted.

Which works fine for nodes, because their names are always quoted on _output_. (Other entities, like graphs, don't always quote their names on output, which is the real problem IMHO.) If `quote_if_necessary()` is always called on output, then there's no need to store names quoted. And doing so is annoying, and just makes lookup weird.

**Closed** 2024-07-11 21:32 UTC
Labels: bug, dot-language, quoting
