### ISSUE TITLE
setup.py register overwrites author with maintainer

### ISSUE THREAD

**Issue by johnyf** [pydot/pydot#122] opened 2016-05-17 04:20 UTC
This behavior [has been reverted](https://pypi.python.org/pypi/pydot/1.0.29) by hand using PyPI's web interface. It was anticipated from `testpypi.python.org`. After installation, `pip show pydot` still shows the maintainer as author, because `PKG-INFO` remains as uploaded.

Nonetheless, this appears to be [known](https://bugs.python.org/issue12840) and [intended behavior](https://bugs.python.org/issue962772), though somewhat misimplemented.

**Comment by peternowee** [comment] 2021-02-15 18:01
I am not seeing this issue anymore with packages for 1.4.2 uploaded to test.pypi.org and pypi.org. The page for [pydot 1.4.2 on PyPI.org](https://pypi.org/project/pydot/1.4.2/) shows Author as Ero Carrera and Maintainer as myself, as intended and without the need for manual editing.

If I understand correctly, various packaging tools lacked support for the Maintainer-field and this issue was not solved in all of them. Bug reports for various packaging tools:

- distutils: https://bugs.python.org/issue33069, https://github.com/python/cpython/pull/6106, https://bugs.python.org/issue12840. All indicate that this won't be solved there because distutils was being phased out in favor of setuptools. See also: [Differences between distribute, distutils, setuptools and distutils2](https://stackoverflow.com/questions/6344076/differences-between-distribute-distutils-setuptools-and-distutils2/14753678#14753678).
- distutils2: https://bugs.python.org/issue962772. Seems that it was solved there, but I am not using distutils2, so I did not investigate further.
- setuptools: https://github.com/pypa/setuptools/pull/1294/ Seems solved there. The commits there were first part of setuptools v38.7.0, which was released 2018-03-17.

`pip show pydot` only shows `Author: Ero Carrera`, so that field is filled in correctly as well. `Maintainer` is not shown, but it is present in the metadata. This is just the way `pip` presents it, also for other packages that have both an `Author` and a `Maintainer`, such as NetworkX (`pip show networkx`).

`METADATA` in the wheel package and `PKG-INFO` in the source package both have `Author` and `Maintainer` correctly filled in now.

So, assuming the issue was with setuptools and solved there in 2018, I am closing this issue. Feel free to reopen or mention me if I misunderstood.

Versions used:
- For `python setup.py sdist bdist_wheel`: Python 3.7.3+pip 21.0.1+setuptools 53.0.0.
- For `pip install`: Python 3.7.3+pip 21.0.1+setuptools 53.0.0 and Python 2.7.16+pip 20.3.4+setuptools 44.1.1.

**Closed by peternowee** 2021-02-15 18:01 UTC
