### ISSUE TITLE
wrong position format for neato

### ISSUE THREAD

**Issue by parthi2929** [pydot/pydot#174] opened 2018-05-08 17:23 UTC
Hi

I am trying to render pydot to graphviz (currently via file write and read) with neato engine. 
However I observe, position format is wrong. Below is the code. 

```
# networx to pydot to graphviz
P = nx.nx_pydot.to_pydot(G)
nx.nx_pydot.write_dot(G,'test.dot')                 # write to dot file
(graph,) = pydot.graph_from_dot_file('test.dot')    # read to dot file
print(graph)

# before sending to neato, fix the pos values
# 1. A [pos="(21.31227, 46.18656)"]; should become A [pos="21.31227, 46.18656!"];
# src = Source(graph, engine='neato',format='png')
# src.render('test1', view=True)  
```

Can you please explain how to fix that issue? Why pydot introduces braces in pos?

**Comment by johnyf** [comment] 2018-05-08 23:55
Thanks for reporting an issue, could you please provide a script that produces this behavior.

**Comment by parthi2929** [comment] 2018-05-09 03:14
Please find the complete script below. I think, the braces come from pos, but that is the form from which I feed networkx. 

```
import networkx as nx 
import pydot
from graphviz import Source, render

romania_location_map = {
    'A' : {'pos': (21.31227,46.18656), 'connections': ['S','T','Z'] },
    'S' : {'pos': (24.12558,45.79833), 'connections': ['F','RV','O'] },
    'Z' : {'pos': (21.51742,46.62251), 'connections': ['O'] },
    'T' : {'pos': (21.20868,45.74887), 'connections': ['LU'] },
    'O' : {'pos': (21.91894,47.04650), 'connections': [] },
    'F' : {'pos': (24.97310,45.84164), 'connections': ['B'] },
    'LU' : {'pos': (21.90346,45.69099), 'connections': ['M'] },
    'RV' : {'pos': (24.36932,45.09968), 'connections': ['C','P'] },
    'M' : {'pos': (22.36452,44.90411), 'connections': ['D'] },
    'D' : {'pos': (22.65973,44.63692), 'connections': ['C'] },
    'C' : {'pos': (23.79488,44.33018), 'connections': [] },
    'P' : {'pos': (24.86918,44.85648), 'connections': ['B','C'] },
    'B' : {'pos': (26.10254,44.42677), 'connections': ['G','U'] },
    'G' : {'pos': (25.96993,43.90371), 'connections': [] },
    'U' : {'pos': (26.64112,44.71653), 'connections': ['H','V'] },
    'V' : {'pos': (27.72765,46.64069), 'connections': ['LA'] },
    'LA' : {'pos':(27.60144,47.15845), 'connections': ['N'] },
    'N' : {'pos': (26.38188,46.97587), 'connections': [] },
    'H' : {'pos': (27.94566,44.68935), 'connections': ['E'] },
    'E' : {'pos': (28.65273,44.04911), 'connections': [] }
}

G = nx.Graph()
Map = romania_location_map

for node in Map.keys():
    G.add_node(node, pos=Map[node]['pos'])
for node in Map.keys():
    for con_node in Map[node]['connections']:
        G.add_edge(node, con_node, length=10)

for edge in G.edges():
	x0, y0 = G.node[edge[0]]['pos']
	x1, y1 = G.node[edge[1]]['pos']
	#print('Point 1 of Edge:',x0, y0)
	#print('Point 2 of Edge:',x1, y1)
	#print(G.node[edge[0]])

for node in G.nodes():
	x, y = G.node[node]['pos']
	#print('Node location:',x, y)



# networx to pydot to graphviz
P = nx.nx_pydot.to_pydot(G)
nx.nx_pydot.write_dot(G,'test.dot')                 # write to dot file
(graph,) = pydot.graph_from_dot_file('test.dot')    # read to dot file
print(graph)

# before sending to neato, fix the pos values
# 1. A [pos="(21.31227, 46.18656)"]; should become A [pos="21.31227, 46.18656!"];
# src = Source(graph, engine='neato',format='png')
# src.render('test1', view=True)  

```

**Comment by parthi2929** [comment] 2018-05-10 04:12
New code without having to write and read dot file.. Apparently this also means, pydot returned by networkx should be fixed instead or pydot should have been stripping the pos tuple braces automatically?

```
# networx to pydot to graphviz
P = nx.nx_pydot.to_pydot(G)
print(str(P))                    # directly getting graphviz output

# before sending to neato, fix the pos values
# 1. A [pos="(21.31227, 46.18656)"]; should become A [pos="21.31227, 46.18656!"];
# src = Source(str(P), engine='neato',format='png')
# src.render('test1', view=True)  

```

**Comment by peternowee** [comment] 2020-09-05 17:20
@parthi2929 Not sure if you are still interested in an answer more than 2 years after reporting, but I still had a look to see if we can learn something from what you experienced.

First, I reduced your example code to a minimum:

```python3
import networkx as nx 

G = nx.Graph()
G.add_node('A', pos=(21.31227,46.18656))
P = nx.nx_pydot.to_pydot(G)
print(str(P))
```

Output:
```dot
strict graph  {
A [pos="(21.31227, 46.18656)"];
}
```

Stepping through the NetworkX source code, I further reduced it to pure pydot:

**Minimal reproducible example**

```python3
import pydot

P = pydot.Dot()
p = pydot.Node('A', pos='(21.31227, 46.18656)'})
P.add_node(p)
print(str(P))
```

Output:
```dot
digraph G {
A [pos="(21.31227, 46.18656)"];
}
```

I will consider this second example to be the [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) or [Minimal Working Example](https://en.wikipedia.org/wiki/Minimal_working_example) for this issue.

Side note 1: In case you are wondering why in the second example the `pos` coordinates are not passed as a tuple anymore, but as a string: That is because internally, even in your example code, NetworkX casts the tuple to string before sending it to pydot. See [`str(v)` in NetworkX 2.5](https://github.com/networkx/networkx/blob/networkx-2.5/networkx/drawing/nx_pydot.py#L209) for example.

Side note 2: I did try passing a tuple directly to pydot, but that surfaced a bug that pydot does not quote it when writing it as a DOT-string, which then leads to an error message from Graphviz. There are still a few open issues about quoting that I need to go through, so I will add it to one of those or open a new one for that later.

Coming back to the issue you raised: This is the **actual result**:

    A [pos="(21.31227, 46.18656)"];

And from what I understand, this was your **expected result**:

    A [pos="21.31227, 46.18656!"];

Related [Graphviz documentation](https://www.graphviz.org/doc/info/attrs.html) on attribute `pos` of type `point`:
> `pos`: Position of node, or spline control points. For nodes, the position indicates the center of the node. On output, the coordinates are in `points`. [..]
> `point`: `"%f,%f('!')?"` representing the point `(x,y)`. The optional `'!'` indicates the node position should not change (input-only). [..]

Your comments suggest that you expected NetworkX or pydot to recognize the tuple you supplied as input for the DOT-attribute-type (`point`) corresponding with the DOT-attribute (`pos`) you gave. And that when asked to write out the DOT-string, either NetworkX or pydot would take the coordinates out of that tuple and format it according to the Graphviz `point` syntax shown above.

Unfortunately, pydot (API or object model) currently does not offer that functionality at the attribute level. It is mostly oblivious to the meaning of the key/value-pairs you pass as attributes. It has Python classes for Graph, Node, Edge and a few more things, but not for attributes; those are just stored as properties of the Node (or Edge or Graph). It does have a list of possible DOT-attributes for nodes, but it only uses that to create getter and setter methods on a Node-object, not to check the supplied value, store it in a special way or convert it to the correct DOT-attribute-type string. So, at the moment, you cannot simply provide a tuple as an attribute value and expect pydot will know what to do with it. Similarly, I also do not see how pydot should have understood that the exclamation point needed to be added.

I considered if your expectations could be considered an enhancement/feature request. But `pos` is just one of the many attribute types defined by DOT/Graphviz and incorporating the entire DOT attribute model in the pydot object model and API would be an enormous effort. Just look at the size of the related [Graphviz documentation](https://www.graphviz.org/doc/info/attrs.html). It would be like re-implementing a large part of Graphviz in Python. Even if we would just start with `pos`, we would still need to think very carefully about how we start, because that will also determine how we add more attributes after that. I added it to my long-term wishlist, and people who want to start up a discussion on this subject or submit a PR are welcome to do so of course, but keeping this issue here open until then as an "enhancement request" would be overly optimistic, I think.

As far as I know, NetworkX is also not aware of the DOT-specific meanings of attributes like `pos`. But you better ask them directly if you want to be sure.

Also about NetworkX, you wrote:

> I think, the braces come from pos, but that is the form from which I feed networkx.

I do not know exactly what you mean, but maybe you were trying to do something like [this](https://stackoverflow.com/questions/11804730/networkx-add-node-with-specific-position/11809184#11809184). Judging by the example code shown there, I think that you are free to choose any attribute name, not necessarily `pos`, to store the drawing positions for NetworkX. So, maybe you could add your tuple to a different attribute, `pos2` for example. That would allow you to keep the `pos` attribute exclusively for Graphviz and set its value in Graphviz-form from the start.

For example:

```python3
import networkx as nx 

G = nx.Graph()
G.add_node('A', pos='21.31227,46.18656!', pos2=(21.31227,46.18656))
P = nx.nx_pydot.to_pydot(G)
print(str(P))
P.write_png('image.png', prog='neato')
```

Output:

```
strict graph  {
A [pos="21.31227,46.18656!", pos2="(21.31227, 46.18656)"];
}
```
And `image.png`:
![image](https://user-images.githubusercontent.com/10220583/92304815-b255ab80-ef81-11ea-9bc5-fdace111abf9.png)

Finally, note that this does not use the `graphviz` module, because pydot can call `neato` to write the png itself. If you want to view the image on screen, see https://stackoverflow.com/questions/4596962/display-graph-without-saving-using-pydot. This may be something pydot could perhaps make easier, so I will try to see if any of the existing open issues talks about that already or else maybe create a new issue for that later.

Not sure if you still want to add anything? If I do not hear from you, I will close this issue in one or two weeks probably. You can reopen later as well, of course. Either way, thanks for reporting! It is always interesting to see how others are using pydot and it has given me some new ideas.

###### Used versions: Python 3.7.3, NetworkX 2.5, pydot 1.4.1.

**Comment by parthi2929** [comment] 2020-09-08 03:25
@peternowee Great to see the response even after 2 years. I have drifted to other domain now so could not recall immediately the problem I was facing here in detail, but I highly appreciate and thank this detailed answer you have provided, taking the time and pain taken to provide them. Thank you very much. We could close this issue for now.

**Comment by peternowee** [comment] 2020-09-08 06:58
@parthi2929 Yes, I thought you might have moved on. Anyway, thanks for still replying so quickly. It was no problem for me to look into this. Talk to you later maybe and good luck!

**Closed by peternowee** 2020-09-08 06:58 UTC
Labels: api, question
