### ISSUE TITLE
May the .dot file is too large？？

### ISSUE THREAD

**Issue by ghostogay** [pydot/pydot#285] opened 2022-03-31 09:00 UTC
![image](https://user-images.githubusercontent.com/25201531/161017977-8fecd567-d054-41f5-9d2f-743c00564f47.png)
[max_graph.zip](https://github.com/pydot/pydot/files/8387709/max_graph.zip)
The max_graph.zip contains the .dot file, why it cannot read by pydot?

**Comment by ghostogay** [comment] 2022-03-31 09:01
The pydot version is 1.4.2

**Comment by lkk7** [comment] 2024-06-29 19:31
Closing because:
- `dot` gives an error when trying to parse this file, so it's incorrect
- The issue is outdated

**Closed by lkk7** 2024-06-29 19:31 UTC
